default_context:
  package_name: "irispy"
  module_name: "irispy"
  short_description: "A SunPy-affiliated package which provides tools to analyze data from IRIS."
  long_description: "file: README.rst"
  author_name: "The SunPy Community"
  author_email: "sunpy@googlegroups.com"
  license: "BSD 3-Clause"
  project_url: "http://docs.sunpy.org/projects/irispy/"
  project_version: "0.1.0dev"
  include_example_code: "n"
  include_example_cython_code: "n"
  include_cextern_folder: "n"
  edit_on_github_extension: "True"
  github_project: "sunpy/irispy"
  use_azure_ci: "y"
  use_read_the_docs: "y"
  sphinx_theme: "sunpy-sphinx-theme"
  initialize_git_repo: "n"
  minimum_python_version: "3.6"
